config/routes.rb
Rails.application.routes.draw do
  root to: "main#index", as: "root"
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :main, only: [:index]
  resources :users
  resources :categories, only: [:index, :new, :create, :update, :show, :destroy] do
    resources :expenses, only: [:index, :new, :create, :destroy]
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :user
  has_and_belongs_to_many :expense, join_table: 'expense_categories', dependent: :destroy

  validates :name, presence: true, uniqueness: true
  validates :icon, presence: true

  def total_amount
    expense.sum(:amount)
  end
end

app/models/expense.rb
class Expense < ApplicationRecord
  belongs_to :user, foreign_key: 'author_id'
  has_and_belongs_to_many :category, join_table: 'expense_categories', dependent: :destroy

  validates :name, presence: true
  validates :amount, presence: true
end

app/models/expense_category.rb
class ExpenseCategory < ApplicationRecord
  belongs_to :expense
  belongs_to :category
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :category
  has_many :expense

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  protect_from_forgery with: :exception

  before_action :update_allowed_parameters, if: :devise_controller?

  def after_sign_in_path_for(_resource)
    categories_path
  end

  def after_sign_out_path_for(_resource)
    new_user_session_path
  end

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password) }
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password) }
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[show edit update destroy]

  # GET /categories or /categories.json
  def index
    @user = current_user
    @categories = @user.category
  end

  # GET /categories/1 or /categories/1.json
  def show
    @category = Category.find(params[:id])
    @expenses = @category.expense.order(created_at: :desc)
    @categories = current_user.category
  end

  # GET /categories/new
  def new
    @user = current_user
    @category = Category.new
  end

  # POST /categories or /categories.json
  def create
    @user = current_user
    @category = @user.category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to categories_url, notice: 'Category created successfully.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to category_url(@category), notice: 'Category updated successfully .' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category = Category.find(params[:id])
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category deleted successfully.' }
      format.json { head :no_content }
    end
  end

  private

  # Callbacks to share common setup between actions.
  def set_category
    @category = Category.find(params[:id])
  end

  # Allow a list of trusted parameters.
  def category_params
    params.require(:category).permit(:name, :icon)
  end
end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  before_action :set_expense, only: %i[show edit update destroy]

  # GET /expenses or /expenses.json
  def index
    @category = Category.find(params[:category_id])
    @expenses = @category.expense.all
  end

  # GET /expenses/new
  def new
    @author = current_user
    @category = Category.find(params[:category_id])
    @expense = Expense.new
  end

  # POST /expenses or /expenses.json
  def create
    @author = current_user
    saved_expenses = []
    category_ids = params[:expense][:category_ids].reject(&:empty?).map(&:to_i).uniq

    category_ids.each do |c_id|
      @category = Category.find(c_id)
      @expense = Expense.new(expense_params)
      @expense.author_id = current_user.id
      @category.expense << @expense

      if @expense.save
        saved_expenses << @expense
      else
        # Handle the case where an expense can't be saved
        respond_to do |format|
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @expense.errors, status: :unprocessable_entity }
        end
      end
    end

    save?(saved_expenses, category_ids)
    # Redirect to the first category's show page after all expenses have been processed
  end

  # PATCH/PUT /expenses/1 or /expenses/1.json
  def update
    respond_to do |format|
      if @expense.update(expense_params)
        format.html { redirect_to expense_url(@expense), notice: 'Expense updated successfully.' }
        format.json { render :show, status: :ok, location: @expense }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @expense.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /expenses/1 or /expenses/1.json
  def destroy
    @expense.destroy

    respond_to do |format|
      format.html { redirect_to expenses_url, notice: 'Expense successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup between actions.
  def set_expense
    @expense = Expense.find(params[:id])
  end

  # Allow a list of trusted parameters.
  def expense_params
    params.require(:expense).permit(:name, :amount, :author_id)
  end

  def save?(saved_expenses, category_ids)
    if saved_expenses.present?
      redirect_to category_path(category_ids.first), notice: 'Expenses created successfully.'
    else
      # The case where no expenses were successfully saved
      respond_to do |format|
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: { error: 'No expenses saved.' }, status: :unprocessable_entity }
      end
    end
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  skip_before_action :authenticate_user!
  def index; end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index; end

  def show; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/expenses_helper.rb
module ExpensesHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/categories/_category.html.erb
<%= stylesheet_link_tag "categories" %>

<div id="<%= dom_id category %>" class= "category"> 
    <div class="icon-name">
    <img src='<%= category.icon %>'  class= "icon"/>
    <span class="cname">
    <p><%= category.name %></p>
     <p><%= category.created_at.to_date%></p>
    </span>
    </div>
    <p class="tamount">
    $<%=category.total_amount%>
    </p>
</div>

app/views/categories/_form.html.erb
<%=form_with(model: category) do |form| %>
  <% if category.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(category.errors.count, "error") %> did not allow this to be saved:</h2>

      <ul>
        <% category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name ,placeholder: "full name", autofocus:true %>
  </div>

  <div class="field">
    <%= form.label :icon, style: "display: block" %>
    <%= form.text_field :icon , placeholder: "url" , autofocus:true %>
  </div>

  <div class="field actions">
    <%= form.submit "Save", class: "link_to save" %>
  </div>
<% end %>

app/views/categories/index.html.erb
<% content_for :page_title, "Categories" %>
<%= link_to "New category", new_category_path, class: "link_to newcat" %>
<h1>Categories</h1>

<div id="categories">
  <% @categories.each do |category| %>
     <%= link_to render(category), category_path(category) %>
  <% end %>
</div>

app/views/categories/new.html.erb
<%= stylesheet_link_tag "form" %>
<%= stylesheet_link_tag "categories" %>
<% content_for :page_title, "New Category" %>
<div>
  <%= link_to " < Back", categories_path, class:"link_to back"%>
</div>
<h1>New category</h1>
<section  class = "new_cat">
<%= render "form", category: @category %>
</section>
<br>

app/views/categories/show.html.erb
<%= stylesheet_link_tag "categories" %>
<% content_for :page_title, "Expenses" %>
<p class="tamountE"> Total Amount: <%= @category.total_amount%> </p>

<div id="expenses">
  <% @expenses.each do |expense| %>
    <%= render expense %>
  <% end %>
</div>

<div >
  <div class = "links" >
  <%= link_to "Back to categories", categories_path , class: "link_to"%>
  <%= link_to "New expense", new_category_expense_path(@category) , class: "link_to" %>
  </div>
  <%= button_to "Delete this category", @category, method: :delete , class: "link_to delete" %>
</div>

app/views/expenses/_expense.html.erb
<%= stylesheet_link_tag "categories" %>
<div id="<%= dom_id expense %>", class ="expense">
  <p>
    <strong>Name:</strong>
    <%= expense.name %>
  </p>

  <p>
    <strong>Amount:</strong>
    <%= expense.amount %>
  </p>

</div>

app/views/expenses/_form.html.erb
<%= form_with(model: [@category, @expense]) do |form| %>
  <% if expense.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(expense.errors.count, "error") %> prohibited this expense from being saved:</h2>

      <ul>
        <% expense.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div  class = "field">
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name , required: true %>
  </div>

  <div  class = "field">
    <%= form.label :amount, style: "display: block" %>
    <%= form.text_field :amount , required: true%>
  </div>

  <div class="checkbox-exp">
  <%= form.label :categories %>
  <%= form.collection_check_boxes(:category_ids, @author.category.all, :id, :name) do |b| %>
    <div class="checkbox">
      <%= b.check_box %>
      <%= b.label %>
    </div>
  <% end %>
</div>

  <div  class = "field actions">
    <%= form.submit 'Save', class: "link_to saveexp" %>
  </div>
<% end %>

app/views/expenses/index.html.erb
<% content_for :page_title, "Expenses" %>

<h1>Expenses</h1>

<div id="expenses">
  <% @expenses.each do |expense| %>
    <%= render expense %>
  <% end %>
</div>

<%= link_to "New expense", new_category_expense_path %>

app/views/expenses/new.html.erb
<%= stylesheet_link_tag "form" %>
<%= stylesheet_link_tag "categories" %>

<div>
  <%= link_to " < Back", category_path(@category) , class:"link_to back" %>
</div>

<% content_for :page_title, "New Expense" %>
<section class = "new-exp">
<%= render "form", expense: @expense %>
</section>
<br>

app/views/expenses/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @expense %>

<div>
  <%= link_to "Edit this expense", edit_expense_path(@expense) %> |
  <%= link_to "Back to expenses", expenses_path %>
  <%= button_to "Delete this expense", @expense, method: :delete %>
</div>

app/views/layouts/_nav.html.erb
<ul class="navbar">
    <li class="dropdown">
        <a class="btn dropbtn"><i class="fa-solid fa-bars"></i></a>
            <div class="dropdown-content">
            <%= link_to 'Home',  categories_path , class: " pages-links btn-home" %>
            <%= link_to 'Log out', destroy_user_session_path ,  data: { turbo_method: :delete } ,class: "pages-links btn-recipes"%>
            </div>
    </li>
    <li> <%= yield :page_title %> </li>
    <li class="searchbtn">
        <i class="fa-solid fa-search"></i>
    </li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsBudgetApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/48a75e5b8e.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.0/css/all.min.css">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <header>
    <% if user_signed_in? %>
        <%= render "layouts/nav" %>
    <%end%>
   </header>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
    
    <%= javascript_include_tag 'splash_screen' %>
  </body>
</html>

app/views/main/index.html.erb
<%= stylesheet_link_tag "splash" %>
<%= render partial: 'splash/splash' %>

<p style="color: green"><%= notice %></p>
<div id="mains">
<h1 class="topicm"> SpendWise </h1>
<%= link_to "Log in", new_user_session_path , class: "link_to login"%>
<%= link_to "Sign up", new_user_registration_path, class: "link_to login signup" %>

</div>

app/views/splash/_splash.html.erb
<%= stylesheet_link_tag "splash" %>

<section id='splash-screen'>
  <div class="topic">
    <h1 class="heading">SpendWise</h1>
    <%= image_tag "img_inr.jpg", class: "image" %>
  </div>
  <div class="welcome">
    <p >
      Welcome to SpendWise
    </p>
    <p>
      Smart Spending, Happy Living..!!
    </p>
  </div>
  <div class="start">
    <%= link_to "Go", new_user_session_path, class: "link_to start-link" %>
  </div>
</section>